# -*- coding: utf-8 -*-
"""ML_medflux_Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DIMGkSEtR8gDhmCH4s8EquJMHeBPq830
"""

from google.colab import drive
drive.mount('/content/drive')

"""Project Folder Create"""

import os

base_path = "/content/drive/MyDrive/medflux_ml"

folders = [
    "data",
    "models",
    "scripts"
]

for f in folders:
    os.makedirs(os.path.join(base_path, f), exist_ok=True)

print("ML Project Structure Created ✅")

"""Dataset Generation Script"""

import random
import pandas as pd
import networkx as nx

def create_network():

    G = nx.DiGraph()

    G.add_node("S1", inventory=120)
    G.add_node("M1", inventory=80)
    G.add_node("D1", inventory=60)
    G.add_node("H1", inventory=40)

    G.add_edges_from([
        ("S1","M1"),
        ("M1","D1"),
        ("D1","H1")
    ])

    return G

def simulate_recovery(shock, centrality, buffer, lead_var):

    recovery = (
        shock*25 +
        centrality*15 +
        lead_var*3 -
        buffer*0.05 +
        random.uniform(-2,2)
    )

    return max(recovery,1)

rows = []

for _ in range(5000):

    G = create_network()

    node = random.choice(list(G.nodes))

    shock = random.uniform(0.1,0.9)

    centrality_dict = nx.betweenness_centrality(G)
    centrality = centrality_dict[node]

    buffer = sum([G.nodes[x]["inventory"] for x in G.nodes])

    lead_var = random.uniform(1,5)

    recovery_time = simulate_recovery(
        shock,
        centrality,
        buffer,
        lead_var
    )

    rows.append([
        shock,
        centrality,
        buffer,
        lead_var,
        recovery_time
    ])

df = pd.DataFrame(rows, columns=[
    "shock",
    "centrality",
    "buffer",
    "lead_var",
    "recovery_time"
])

df.to_csv("/content/drive/MyDrive/medflux_ml/data/dataset.csv", index=False)

print("Dataset Created ✅")

"""Model Training"""

import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

df = pd.read_csv("/content/drive/MyDrive/medflux_ml/data/dataset.csv")

X = df[["shock","centrality","buffer","lead_var"]]
y = df["recovery_time"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestRegressor()

model.fit(X_train, y_train)

score = model.score(X_test, y_test)

print("R2 Score:", score)

joblib.dump(model, "/content/drive/MyDrive/medflux_ml/models/recovery_model.pkl")

print("Model Saved ✅")

"""Prediction Function"""

import joblib
import pandas as pd

model = joblib.load("/content/drive/MyDrive/medflux_ml/models/recovery_model.pkl")

def predict_recovery(shock, centrality, buffer, lead_var):

    data = pd.DataFrame([{
        "shock": shock,
        "centrality": centrality,
        "buffer": buffer,
        "lead_var": lead_var
    }])

    prediction = model.predict(data)

    return float(prediction[0])

"""Test Prediction"""

result = predict_recovery(
    shock=0.6,
    centrality=0.5,
    buffer=300,
    lead_var=3
)

print("Predicted Recovery:", result)

for shock in [0.2, 0.5, 0.8]:
    print(shock, predict_recovery(shock, 0.3, 250, 2))

"""Random Network Generator"""

import random
import networkx as nx

def create_random_network():

    G = nx.DiGraph()

    n_nodes = random.randint(4,8)

    for i in range(n_nodes):
        G.add_node(f"N{i}", inventory=random.randint(20,150))

    nodes = list(G.nodes)

    for _ in range(n_nodes+2):
        u = random.choice(nodes)
        v = random.choice(nodes)
        if u != v:
            G.add_edge(u,v)

    return G

G = create_random_network()

"""More Realistic Features Add"""

network_size = G.number_of_nodes()
avg_degree = sum(dict(G.degree()).values())/network_size

"""XG boost model"""

from xgboost import XGBRegressor

model = XGBRegressor()
model.fit(X_train,y_train)

""" input data

"""

import pandas as pd

data = pd.DataFrame([{
    "shock": 0.6,
    "centrality": 0.5,
    "buffer": 300,
    "lead_var": 3
}])

"""Uncertainty Code"""

import numpy as np

predictions = []

for _ in range(20):

    noise = np.random.normal(0, 0.02)

    new_input = data.copy()
    new_input["shock"] += noise

    pred = model.predict(new_input)[0]

    predictions.append(pred)

mean_pred = np.mean(predictions)
std_pred = np.std(predictions)

print("Prediction:", mean_pred, "±", std_pred)

file_path = "/content/drive/MyDrive/medflux_ml/scripts/ml_model.py"

code = """
import joblib
import pandas as pd
import numpy as np

model = joblib.load("/content/drive/MyDrive/medflux_ml/models/recovery_model.pkl")

def predict_recovery(shock, centrality, buffer, lead_var):

    data = pd.DataFrame([{
        "shock": shock,
        "centrality": centrality,
        "buffer": buffer,
        "lead_var": lead_var
    }])

    pred = model.predict(data)[0]

    return float(pred)

def predict_with_uncertainty(shock, centrality, buffer, lead_var):

    data = pd.DataFrame([{
        "shock": shock,
        "centrality": centrality,
        "buffer": buffer,
        "lead_var": lead_var
    }])

    preds = []

    for _ in range(20):

        noise = np.random.normal(0,0.02)

        temp = data.copy()
        temp["shock"] += noise

        p = model.predict(temp)[0]
        preds.append(p)

    mean_pred = np.mean(preds)
    std_pred = np.std(preds)

    return float(mean_pred), float(std_pred)
"""

with open(file_path, "w") as f:
    f.write(code)

print("ml_model.py Created ✅")

import sys
sys.path.append("/content/drive/MyDrive/medflux_ml/scripts")

import medflux.backend.old_ml_model as old_ml_model

print(old_ml_model.predict_recovery(0.6,0.4,250,3))

for s in [0.2,0.4,0.6,0.8]:
    print(s, old_ml_model.predict_recovery(s,0.4,250,3))

import medflux.backend.old_ml_model as old_ml_model

old_ml_model.predict_recovery(0.6,0.3,200,2)

def predict_from_graph(G, shock_node, shock_mag):

    import networkx as nx

    centrality = nx.betweenness_centrality(G)[shock_node]
    buffer = sum(nx.get_node_attributes(G,"inventory").values())
    lead_var = 2   # assumed

    return predict_recovery(shock_mag, centrality, buffer, lead_var)

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/medflux_ml/data/dataset.csv"
)

df.head()

"""Feature Importance & Model Insights"""

import joblib
import pandas as pd
import matplotlib.pyplot as plt

# Load model
model = joblib.load("/content/drive/MyDrive/medflux_ml/models/recovery_model.pkl")

# Dataset for features
df = pd.read_csv("/content/drive/MyDrive/medflux_ml/data/dataset.csv")
features = ["shock","centrality","buffer","lead_var"]

# Feature importance
importances = model.feature_importances_

plt.bar(features, importances)
plt.title("Feature Importance")
plt.show()

for f, imp in zip(features, importances):
    print(f"{f}: {imp:.3f}")

"""Model Prediction Function"""

prediction = predict_recovery(shock=0.6, centrality=0.5, buffer=300, lead_var=3)
print("Predicted Recovery:", prediction)

"""Add Uncertainty / Confidence"""

import numpy as np

def predict_with_uncertainty(model, data):
    preds = np.array([tree.predict(data)[0] for tree in model.estimators_])
    mean = preds.mean()
    std = preds.std()
    return mean, std

# Example
import pandas as pd
data = pd.DataFrame([{"shock":0.6,"centrality":0.5,"buffer":300,"lead_var":3}])
mean, std = predict_with_uncertainty(model, data)
print(f"Prediction: {mean:.3f} ± {std:.3f}")

"""Save Final ML Code (ml_model.py)"""

import pandas as pd
import joblib
import numpy as np

BASE_PATH = "/content/drive/MyDrive/medflux_ml"

# Load trained model
model = joblib.load(f"{BASE_PATH}/models/recovery_model.pkl")

def predict_recovery(shock, centrality, buffer, lead_var):
    data = pd.DataFrame([{
        "shock": shock,
        "centrality": centrality,
        "buffer": buffer,
        "lead_var": lead_var
    }])
    prediction = model.predict(data)
    return float(prediction[0])

def predict_with_uncertainty(shock, centrality, buffer, lead_var):
    data = pd.DataFrame([{
        "shock": shock,
        "centrality": centrality,
        "buffer": buffer,
        "lead_var": lead_var
    }])
    preds = np.array([tree.predict(data)[0] for tree in model.estimators_])
    return preds.mean(), preds.std()

import warnings
warnings.filterwarnings("ignore", category=UserWarning)

import numpy as np
import pandas as pd

data = pd.DataFrame([{"shock":0.6,"centrality":0.5,"buffer":300,"lead_var":3}])

# Convert to numpy array
X = data.values

preds = np.array([tree.predict(X)[0] for tree in model.estimators_])
mean = preds.mean()
std = preds.std()
print(f"Prediction: {mean:.3f} ± {std:.3f}")

importances = model.feature_importances_
print(dict(zip(["shock","centrality","buffer","lead_var"], importances)))

from fastapi import FastAPI
from medflux.backend.old_ml_model import predict_with_uncertainty  # ensure yeh function define hai

# FastAPI app create
app = FastAPI()

# Prediction endpoint
@app.post("/predict_recovery")
def predict(data: dict):
    shock = data["shock"]
    centrality = data["centrality"]
    buffer = data["buffer"]
    lead_var = data["lead_var"]

    pred, std = predict_with_uncertainty(shock, centrality, buffer, lead_var)
    return {"prediction": pred, "uncertainty": std}

shock = 0.6
centrality = 0.3
buffer = 250
lead_var = 2.5

pred, std = predict_with_uncertainty(shock, centrality, buffer, lead_var)
print(pred, std)

"""network_loader.py"""

import networkx as nx

def load_network(data):
    """
    Load a network from JSON into a NetworkX DiGraph.

    Args:
        data: dict
            {
                "nodes": [
                    {"id":"S1", "type":"supplier", "inventory":100, "demand":0},
                    ...
                ],
                "edges": [
                    {"source":"S1","target":"M1","capacity":100, "transport_time":2},
                    ...
                ]
            }

    Returns:
        G: networkx.DiGraph
    """
    G = nx.DiGraph()

    # Add nodes
    for node in data.get("nodes", []):
        G.add_node(
            node["id"],
            type=node.get("type", "unknown"),
            inventory=node.get("inventory", 0),
            demand=node.get("demand", 0),
            lead_time=node.get("lead_time", 1)  # optional attribute
        )

    # Add edges
    for edge in data.get("edges", []):
        G.add_edge(
            edge["source"],
            edge["target"],
            capacity=edge.get("capacity", 100),
            transport_time=edge.get("transport_time", 1)  # optional
        )

    print(f"Loaded network with {G.number_of_nodes()} nodes and {G.number_of_edges()} edges.")
    return G

"""simulation.py"""

# backend/simulation.py
import networkx as nx

def simulate(G, steps=30):
    """
    Run a basic inventory simulation over a network.

    Args:
        G: networkx.DiGraph
        steps: number of timesteps

    Returns:
        history: list of dicts, each dict = {node_id: inventory}
    """
    history = []

    for t in range(steps):
        # Update inventory for each node
        for node in G.nodes:
            inv = G.nodes[node]["inventory"]
            demand = G.nodes[node].get("demand", 0)
            # Inventory consumed by demand
            inv = max(inv - demand, 0)
            G.nodes[node]["inventory"] = inv

            # Optional: propagate inventory downstream if edges exist
            for succ in G.successors(node):
                edge_capacity = G.edges[node, succ].get("capacity", 100)
                # Send min of node inventory or edge capacity
                transfer = min(inv, edge_capacity)
                G.nodes[succ]["inventory"] += transfer
                G.nodes[node]["inventory"] -= transfer

        # Record snapshot of current inventory
        history.append({n: G.nodes[n]["inventory"] for n in G.nodes})

    return history


def inject_shock(G, node_id, magnitude=0.5):
    """
    Apply a shock to a node by reducing its inventory.

    Args:
        G: networkx.DiGraph
        node_id: str
        magnitude: float (0-1), fraction to reduce
    """
    if node_id in G.nodes:
        G.nodes[node_id]["inventory"] *= (1 - magnitude)
        print(f"Injected shock at {node_id}: new inventory = {G.nodes[node_id]['inventory']}")


def predict_from_sim(history, node_id):
    """
    Optional: simple recovery metric.
    Returns peak shortage for a node.
    """
    inv_list = [step[node_id] for step in history]
    peak = max(inv_list)
    min_inv = min(inv_list)
    shortage = peak - min_inv
    return shortage

"""ML Module Integration with Simulation"""

# simulation.py ke andar
from medflux.backend.old_ml_model import predict_with_uncertainty
import networkx as nx

def predict_from_sim(G, shock_node, shock_mag):
    centrality = nx.betweenness_centrality(G).get(shock_node, 0)
    buffer = sum(nx.get_node_attributes(G,"inventory").values())
    lead_var = 2  # default ya calculation

    mean, std = predict_with_uncertainty(shock_mag, centrality, buffer, lead_var)
    return mean, std

"""Optimizer Module (Buffer / Resilience Recommendation)"""

# optimizer.py
def recommend_buffers(G, total_buffer=300):
    import networkx as nx
    centrality = nx.betweenness_centrality(G)
    total_centrality = sum(centrality.values())
    recommended = {}
    for node in G.nodes:
        weight = centrality[node] / total_centrality
        recommended[node] = total_buffer * weight
    return recommended

"""FastAPI Endpoints for Frontend"""

import os

scripts_path = "/content/drive/MyDrive/medflux_ml/scripts"
os.listdir(scripts_path)

import os

# Base path for scripts
scripts_path = "/content/drive/MyDrive/medflux_ml/scripts/backend"
os.makedirs(scripts_path, exist_ok=True)

# 1️⃣ network_loader.py
network_loader_code = """
import networkx as nx

def load_network(data):
    \"""
    data: {
        "nodes": [{"id":"S1","type":"supplier","inventory":100}, ...],
        "edges": [{"source":"S1","target":"M1","capacity":100}, ...]
    }
    \"""
    G = nx.DiGraph()
    for node in data["nodes"]:
        G.add_node(
            node["id"],
            type=node.get("type"),
            inventory=node.get("inventory",0),
            demand=node.get("demand",0)
        )
    for edge in data["edges"]:
        G.add_edge(
            edge["source"],
            edge["target"],
            capacity=edge.get("capacity",100)
        )
    return G
"""

with open(os.path.join(scripts_path, "network_loader.py"), "w") as f:
    f.write(network_loader_code)


# 2️⃣ simulation.py
simulation_code = """
import networkx as nx

def simulate(G, steps=30):
    history = []

    for t in range(steps):
        for node in G.nodes:
            inv = G.nodes[node]["inventory"]
            demand = G.nodes[node].get("demand", 0)
            inv = max(inv - demand, 0)
            G.nodes[node]["inventory"] = inv

            for succ in G.successors(node):
                edge_capacity = G.edges[node, succ].get("capacity", 100)
                transfer = min(inv, edge_capacity)
                G.nodes[succ]["inventory"] += transfer
                G.nodes[node]["inventory"] -= transfer

        history.append({n: G.nodes[n]["inventory"] for n in G.nodes})

    return history

def inject_shock(G, node_id, magnitude=0.5):
    if node_id in G.nodes:
        G.nodes[node_id]["inventory"] *= (1 - magnitude)
        print(f"Injected shock at {node_id}: new inventory = {G.nodes[node_id]['inventory']}")

def predict_from_sim(history, node_id):
    inv_list = [step[node_id] for step in history]
    peak = max(inv_list)
    min_inv = min(inv_list)
    shortage = peak - min_inv
    return shortage
"""

with open(os.path.join(scripts_path, "simulation.py"), "w") as f:
    f.write(simulation_code)

print("✅ network_loader.py and simulation.py saved in scripts/backend")

from backend.network_loader import load_network
from backend.simulation import simulate, inject_shock, predict_from_sim

import os

scripts_path = "/content/drive/MyDrive/medflux_ml/scripts"
file_path = os.path.join(scripts_path, "optimizer.py")

code = """
import networkx as nx

def recommend_buffers(G, total_buffer=300):
    centrality = nx.betweenness_centrality(G)
    total_centrality = sum(centrality.values())
    recommended = {}
    for node in G.nodes:
        weight = centrality[node] / total_centrality if total_centrality > 0 else 0
        recommended[node] = total_buffer * weight
    return recommended
"""

with open(file_path, "w") as f:
    f.write(code)

print("optimizer.py Created ✅")

import os

base_path = "/content/drive/MyDrive/medflux_ml/scripts"
backend_path = os.path.join(base_path, "backend")
os.makedirs(backend_path, exist_ok=True)

print("Backend folder ready ✅")

network_loader_code = """
import networkx as nx

def load_network(data):
    G = nx.DiGraph()
    for node in data["nodes"]:
        G.add_node(
            node["id"],
            type=node.get("type"),
            inventory=node.get("inventory",0),
            demand=node.get("demand",0)
        )
    for edge in data["edges"]:
        G.add_edge(
            edge["source"],
            edge["target"],
            capacity=edge.get("capacity",100),
            transport_time=edge.get("transport_time",1)
        )
    print(f"Loaded network with {G.number_of_nodes()} nodes and {G.number_of_edges()} edges.")
    return G
"""

with open(os.path.join(backend_path, "network_loader.py"), "w") as f:
    f.write(network_loader_code)

simulation_code = """
import networkx as nx
from ml_model import predict_with_uncertainty

def simulate(G, steps=30):
    history = []
    for t in range(steps):
        for node in G.nodes:
            inv = G.nodes[node]["inventory"]
            demand = G.nodes[node].get("demand", 0)
            inv = max(inv - demand, 0)
            G.nodes[node]["inventory"] = inv
            for succ in G.successors(node):
                edge_capacity = G.edges[node, succ].get("capacity",100)
                transfer = min(inv, edge_capacity)
                G.nodes[succ]["inventory"] += transfer
                G.nodes[node]["inventory"] -= transfer
        history.append({n: G.nodes[n]["inventory"] for n in G.nodes})
    return history

def inject_shock(G, node_id, magnitude=0.5):
    if node_id in G.nodes:
        G.nodes[node_id]["inventory"] *= (1 - magnitude)
        print(f"Injected shock at {node_id}: new inventory = {G.nodes[node_id]['inventory']}")

def predict_from_sim(G, shock_node, shock_mag):
    centrality = nx.betweenness_centrality(G).get(shock_node,0)
    buffer = sum(nx.get_node_attributes(G,"inventory").values())
    lead_var = 2
    mean, std = predict_with_uncertainty(shock_mag, centrality, buffer, lead_var)
    return mean, std
"""

with open(os.path.join(backend_path, "simulation.py"), "w") as f:
    f.write(simulation_code)

optimizer_code = """
import networkx as nx

def recommend_buffers(G, total_buffer=300):
    centrality = nx.betweenness_centrality(G)
    total_centrality = sum(centrality.values())
    recommended = {}
    for node in G.nodes:
        weight = centrality[node] / total_centrality if total_centrality>0 else 0
        recommended[node] = total_buffer * weight
    return recommended
"""

with open(os.path.join(base_path, "optimizer.py"), "w") as f:
    f.write(optimizer_code)

print("All backend files created ✅")


from backend.network_loader import load_network
from backend.simulation import simulate, inject_shock, predict_from_sim
from optimizer import recommend_buffers
